ValueError: Invalid integer data type 'f'.
https://github.com/andrewekhalel/sewar/blob/ac76e7bc75732fde40bb0d3908f4b6863400cc27/sewar/full_ref.py#L65

np.iinfo() does not work with float data-type as input and raises error: ValueError: Invalid integer data type 'f'.
Therefore, use np.finfo() instead.

For reference, check the Numpy Github link: https://github.com/numpy/numpy/issues/14400